name: Zig build

on:
  push:
    branches:
      - zig-build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # matrix:
      #   compiler: [g++, clang]
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          submodules: recursive

      # fix a package dependency bug in Ubuntu 22.04
      # https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1991919
      # https://github.com/kadalu-tech/pkgs/pull/2/files#r1001042597
      - name: Install dependency
        run: |
          dep_packages=(
              doxygen
              libboost-filesystem-dev
              libboost-locale-dev
              libboost-regex-dev
              libboost-system-dev
          )
          sudo apt update -y
          sudo apt install -y libunwind-dev
          sudo apt install -y ${dep_packages[@]}

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0-dev.2680+a1aa55ebe

      - name: Build
        run: zig build
